# Generated by Django 4.2.10 on 2024-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruits', 'Fruits'), ('Grains', 'Grains')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank='True', null='True', upload_to='products/'),
        ),
    ]
