# Generated by Django 4.2.10 on 2024-02-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0003_alter_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank='True', null='True', upload_to='images/'),
        ),
    ]
