# Generated by Django 4.2.10 on 2024-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
