# Generated by Django 4.2.10 on 2024-03-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('id_front', models.ImageField(blank='True', null='True', upload_to='verifications/')),
                ('id_back', models.ImageField(blank='True', null='True', upload_to='verifications/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=50)),
            ],
        ),
    ]
