# Generated by Django 4.2.10 on 2024-03-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MavunoDigital', '0006_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
