# Generated by Django 4.2.10 on 2024-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0008_alter_farmer_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', editable=False, max_length=50),
        ),
    ]
