# Generated by Django 4.2.7 on 2024-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0012_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
    ]
