# Generated by Django 4.2.7 on 2024-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0013_product_is_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=4),
        ),
    ]
