# Generated by Django 4.2.7 on 2024-03-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MavunoDigital', '0016_alter_product_is_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sell',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold Out', 'Sold Out')], max_length=20),
        ),
    ]
